print("Welcome to the tip calculator!")
total = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? %"))
people = int(input("How many people to split the bill? "))
pay = round(total*(1+tip/100)/people,2)
print(f"Each person should pay: ${pay}")